### ISSUE TITLE
Unsupported target version: 0.24.0 on MacOS

### ISSUE THREAD

**Issue by makenai** [paulcbetts/electron-rebuild#1]
So far I haven't been able to get this to work. I've tried with electron 24 and the latest, and also iojs1.8.0, 2.0 and a slew of node versions. Am I doing something wrong?

```
~/Projects/robotnik (ElectronAndChrome ✘)✹✭ ᐅ node_modules/.bin/electron-rebuild 

> serialport@1.6.3 install /Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.24.0

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.24.0
node-pre-gyp ERR! stack     at get_node_abi (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:27:19)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:133:21)
node-pre-gyp ERR! stack     at install (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/lib/install.js:134:35)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:77:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:130:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "node" "/Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/pawel/Projects/robotnik/node_modules/johnny-five/node_modules/serialport
node-pre-gyp ERR! node -v v0.12.2
node-pre-gyp ERR! node-pre-gyp -v v0.5.19
node-pre-gyp ERR! not ok 

npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/Users/pawel/Projects/robotnik/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.24.0" "--arch=x64"
npm ERR! node v0.12.2
npm ERR! npm  v2.9.0
npm ERR! code ELIFECYCLE
npm ERR! serialport@1.6.3 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.6.3 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/pawel/Projects/robotnik/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/pawel/Projects/robotnik/node_modules/electron-rebuild/lib/spawn.js:53:26)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)
```

**Comment by paulcbetts** [comment]
Hm, I believe this is unique to the serialport project, can you set up a repro?

**Comment by camoedo** [comment]
I have the same problem with 0.26.0 version

Claudios-MacBook-Pro:manager camoedo$ ./node_modules/.bin/electron-rebuild

> serialport@1.7.1 install /Users/camoedo/Google Drive/arduino/manager/node_modules/serialport
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.26.0

node-pre-gyp ERR! install error 
node-pre-gyp ERR! stack Error: Unsupported target version: 0.26.0
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:431:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:449:10)
node-pre-gyp ERR! stack     at Module.load (module.js:356:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:311:12)
node-pre-gyp ERR! System Darwin 14.3.0
node-pre-gyp ERR! command "/Users/camoedo/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/camoedo/Google Drive/arduino/manager/node_modules/serialport/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/camoedo/Google Drive/arduino/manager/node_modules/serialport
node-pre-gyp ERR! node -v v2.0.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.7
node-pre-gyp ERR! not ok 

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/camoedo/.nvm/versions/io.js/v2.0.0/bin/iojs" "/Users/camoedo/Google Drive/arduino/manager/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.26.0" "--arch=x64"
npm ERR! node v2.0.0
npm ERR! npm  v2.10.0
npm ERR! code ELIFECYCLE
npm ERR! serialport@1.7.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the serialport@1.7.1 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the serialport package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls serialport
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/camoedo/Google Drive/arduino/manager/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/camoedo/Google Drive/arduino/manager/node_modules/electron-rebuild/lib/spawn.js:53:26)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:169:7)
    at maybeClose (child_process.js:953:16)
    at Socket.<anonymous> (child_process.js:1114:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:166:7)
    at Pipe._onclose (net.js:456:12)

**Comment by doc** [comment]
Hey Guys, having the same issues here with 0.27.1 and sqlite3 module.

[mporter:~/projects/axn_offline]$ ./node_modules/.bin/electron-rebuild -f

> sqlite3@3.0.7 install /Users/mporter/projects/axn_offline/node_modules/sqlite3
> node-pre-gyp install --fallback-to-build

Unsupported target version: 0.27.1

node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: Unsupported target version: 0.27.1
node-pre-gyp ERR! stack     at get_runtime_abi (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:140:23)
node-pre-gyp ERR! stack     at Object.module.exports.evaluate (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/lib/util/versioning.js:249:19)
node-pre-gyp ERR! stack     at install (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/lib/install.js:138:31)
node-pre-gyp ERR! stack     at Object.self.commands.(anonymous function) [as install] (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/lib/node-pre-gyp.js:48:37)
node-pre-gyp ERR! stack     at run (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:79:30)
node-pre-gyp ERR! stack     at Object.<anonymous> (/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/node-pre-gyp/bin/node-pre-gyp:131:1)
node-pre-gyp ERR! stack     at Module._compile (module.js:460:26)
node-pre-gyp ERR! stack     at Object.Module._extensions..js (module.js:478:10)
node-pre-gyp ERR! stack     at Module.load (module.js:355:32)
node-pre-gyp ERR! stack     at Function.Module._load (module.js:310:12)
node-pre-gyp ERR! System Darwin 14.4.0
node-pre-gyp ERR! command "node" "/Users/mporter/projects/axn_offline/node_modules/sqlite3/node_modules/.bin/node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd /Users/mporter/projects/axn_offline/node_modules/sqlite3
node-pre-gyp ERR! node -v v0.12.4
node-pre-gyp ERR! node-pre-gyp -v v0.6.6
node-pre-gyp ERR! not ok

npm ERR! Darwin 14.4.0
npm ERR! argv "node" "/Users/mporter/projects/axn_offline/node_modules/electron-rebuild/node_modules/npm/bin/npm-cli.js" "rebuild" "--target=0.27.1" "--arch=x64"
npm ERR! node v0.12.4
npm ERR! npm  v2.11.0
npm ERR! code ELIFECYCLE
npm ERR! sqlite3@3.0.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@3.0.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! This is most likely a problem with the sqlite3 package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get their info via:
npm ERR!     npm owner ls sqlite3
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/mporter/projects/axn_offline/node_modules/npm-debug.log

Process exited with code: 1
Error: Process exited with code: 1
    at ChildProcess.<anonymous> (/Users/mporter/projects/axn_offline/node_modules/electron-rebuild/lib/spawn.js:53:26)
    at ChildProcess.emit (events.js:110:17)
    at maybeClose (child_process.js:1015:16)
    at Socket.<anonymous> (child_process.js:1183:11)
    at Socket.emit (events.js:107:17)
    at Pipe.close (net.js:485:12)

**Comment by paulcbetts** [comment]
This seems like it's a bug with the `node-pre-gyp` package which we can't really do anything about, can someone file a bug there instead?

**Comment by makenai** [comment]
Looks like there is one open here that might solve it:

https://github.com/mapbox/node-pre-gyp/issues/110

I'm not familiar with how the native compilation stuff works, but is it possible to work around somehow and not rely on node-pre-gyp, falling back to node-gyp without the fatal error?

**Comment by paulcbetts** [comment]
> I'm not familiar with how the native compilation stuff works, but is it possible to work around somehow and not rely on node-pre-gyp, falling back to node-gyp without the fatal error?

Yeah, so basically, if they didn't use node-pre-gyp at all, this would Just Work. node-pre-gyp seems to be making a simple dumb "If version != one we like, blow up" check

**Comment by makenai** [comment]
Cool, that was my hope. I'll follow this up. When you say "they" in this case, who do you mean?

**Comment by paulcbetts** [comment]
@makenai "they" here is, "the authors of sqlite3 or serialport"

**Comment by paulcbetts** [comment]
Closing as this is almost surely node-pre-gyp not being good
