### ISSUE TITLE
electron-rebuild doesn't seem to do anything on windows :(

### ISSUE THREAD

**Issue by mattvv** [paulcbetts/electron-rebuild#10]
Hey Paul!

Trying to get node-ffi working with electron on windows. Super simple project.

Steps I took:
```
npm install ffi --save
npm install electron-rebuild
```

I then run ./node_modules/.bin/electron-rebuild
And.... nothing happens. Back to the shell. No output or anything and it's super fast. 

When trying to run my electron app I get the 'module did not self-register' error.

Hoping you have some tips for me!
Thanks,

Matt

**Comment by mattvv** [comment]
Closing this issue. Looks like I can get it to work if I force node version and electron version using -v and -n.

**Comment by paulcbetts** [comment]
I think the bug is that electron-rebuild is incorrectly detecting sometimes that it's already built for some reason

**Comment by robinne** [comment]
can someone elaborate on the solution here. I cannot get electron-rebuild to do anything either. what does it mean to force node version and electron version? thanks.
