### ISSUE TITLE
node_modules\.bin\electron-rebuild ends without output

### ISSUE THREAD

**Issue by s-a** [paulcbetts/electron-rebuild#12]
node_modules\.bin\electron-rebuild exits fast and without output. I previously installed fibers. 

``` shell
.bin\electron-rebuild

c:\git\iron-node>node -v
v0.12.6
``` 
Using 
 - Microsoft Windows 7 Home Premium
 - 6.1.7601 Service Pack 1 Build 7601
 - X86-based PC

"electron-prebuilt": "^0.30.0",

**Comment by liuxiong332** [comment]
I also have this problem.

**Comment by paulcbetts** [comment]
Not a bug, this is how UNIX works :)  The exit code should be non-zero on failure (and a message will be printed)

**Comment by liuxiong332** [comment]
I browse the source code, I find the following code:

```js
export async function shouldRebuildNativeModules(pathToElectronExecutable, explicitNodeVersion=null) {
  // Try to load our canary module - if it fails, we know that it's built 
  // against a different node module than ours, so we're good
  //
  // NB: Apparently on OS X, this not only fails to be required, it segfaults
  // the process, because lol.
  try {
    let args = ['-e', 'require("nslog")']
    await spawn({cmd: process.execPath, args});
    
    require('nslog');
  } catch (e) {
    return false;
  }

```
When judge if the module should to be rebuild, the function will require the `nslog` module first. But my 
repo don't dependent this package, so `spawn` will fail and `shouldRebuildNativeModules` will return `false`, then nothing happens.

**Comment by paulcbetts** [comment]
nslog is a module that electron-compile has as a dependency so that's fine, though you definitely found a bug there, it should be `return true`. In the meantime, you can work around this by passing `-f` to always build modules

**Comment by s-a** [comment]
:+1:   ```-f``` works as expected.

**Comment by s-a** [comment]
I do not think this is a problem of your module, but maybe you have an idea? 
I installed fibers post compiled with ```node_modules\.bin\electron-rebuild -f```. My electron app requests a version ```win32-ia32-v8-4.3/fibers.node``` but there is not output for this version? Do you know what I am doing wrong ?

**Comment by liuxiong332** [comment]
The install output is not piped into the cmd. But if you encounter a error when rebuild, the error information will be showed.
So if you don't have output, it's OK.

**Comment by s-a** [comment]
@liuxiong332  so fibers does not provide a matching version for electron?

**Comment by paulcbetts** [comment]
> I do not think this is a problem of your module, but maybe you have an idea? 

This is a common bug with libraries that use node-pre-gyp, they don't correctly fall back to building the module, so rebuild fails - if they just used node-gyp and stopped trying to be clever it would Just Work :-/

**Comment by s-a** [comment]
Do you know how I can force to build a specific version instead the whole bunch? Maybe I can get more details then.
