### ISSUE TITLE
Question re: Electron app distribution process

### ISSUE THREAD

**Issue by joeferraro** [paulcbetts/electron-rebuild#13]
If I'm including a node module in my Electron app that requires native bindings (keytar), do I need to include electron-rebuild as well and rebuild programmatically anytime the app is installed/updated on a user's local machine or is this a one-time process during build, per platform?

**Comment by paulcbetts** [comment]
>  this a one-time process during build, per platform?

^^^ This one, you only need to run electron-rebuild on your dev machine and ship the resulting node_modules folder. Users don't have to have any dev tools on their machine
