### ISSUE TITLE
specifying nodeModulesPath has no effect

### ISSUE THREAD

**Issue by mwhearty** [paulcbetts/electron-rebuild#3]
regardless of what is specified as the nodeModulesPath when invoking rebuildNativeModules, the node_modules under the current directory is used.  looking at the code in main.js this argument appears to be unused.

**Comment by paulcbetts** [comment]
Oops, you're totally right, need to fix that

**Comment by ducky427** [comment]
Can this be closed now that the fix seems to exist in the code (I think)?
