### ISSUE TITLE
"Unable to find electron-prebuilt's version number"

### ISSUE THREAD

**Issue by natevw** [paulcbetts/electron-rebuild#4]
As described in the Electron documentation and this module's README, I simply installed via `npm install --save-dev electron-rebuild` and attempted to use via `./node_modules/.bin/electron-rebuild`.

This only resulted in an error message:

> Unable to find electron-prebuilt's version number, either install it or specify an explicit version

**Comment by natevw** [comment]
It appears that this package requires `npm install electron-prebuilt --save-dev` before it will work as described in its docs. Shouldn't it be listed in its `peerDependencies` then?

**Comment by paulcbetts** [comment]
> Shouldn't it be listed in its peerDependencies then?

No, because you don't actually _need_ electron-prebuilt, you can specify everything yourself, it's just the Easy Mode that needs electron-prebuilt

**Comment by lseongjoo** [comment]
I have the same problem doing the Easy Way.  

electron --version
v 0.30.3

**Comment by Imskull** [comment]
Same problem +1

**Comment by lseongjoo** [comment]
It shows the error message but installed npm modules just works without executing the command line.



2015. 8. 12. 오후 8:42 Imskull <notifications@github.com> 작성:

**Comment by black-snow** [comment]
Yeah... should be added to the "easy way" docs then. Having the same issue here.

**Comment by paulcbetts** [comment]
I'll look into this soon

**Comment by JeevanJain** [comment]
Got error after installing electron-rebuild

    An unhandled error occurred inside electron-rebuild
    Unable to find electron-prebuilt's version number, either install it or specify an explicit version

**Comment by Luiz-N** [comment]
+1

**Comment by yatashashank** [comment]
+1
