### ISSUE TITLE
Silent error breaking installNodeHeaders

### ISSUE THREAD

**Issue by bzuillsmith** [paulcbetts/electron-rebuild#8]
The published npm package v0.2.2 doesn't seem to include the fix in Pull Request #7 which I believe is causing ```installNodeHeaders``` to be broken for me. I'm having trouble catching any errors. Seems to silently fail.
I also can't get npm to successfully install straight from Github to give the latest commits a try.

**Comment by bzuillsmith** [comment]
For the case that the headers don't exist, it will look for the files and error. There seems to be multiple issues going on here:

1. fs.stat throws if the given path does not exist. Therefore this line will throw ```await fs.stat(canary)``` https://github.com/paulcbetts/electron-rebuild/blob/master/src/main.js#L17
2. This thrown error doesn't seem to be catching properly. I'm less familiar with babel and can't find much documentation on its es7 features. I did read that a surrounding try/catch should catch the error according to the specification, but I could not get it to work for me. Perhaps the issue lies in Promisify, but I haven't looked into it.

As a hotfix, I tried making it use fs.statSync and removing the ```promisify``` on fs and ```await``` for that line. It worked, but then I got another issue. The spawn command that is issued exits immediately and the operation never actually runs. I can run the command straight from the command line with the default USERPROFILE variable (which means headers go in the wrong place), but if I change this env variable, it hangs and never times out.

I'm using Windows 8.1 and Node 0.12.x

**Comment by paulcbetts** [comment]
@bzuillsmith These weirdo bugs all sound like the time that Babel runtime broke compatibility with previous versions in a patch... can you try going into `node_modules\electron_rebuild` and doing `npm install` and see if rebuilding against latest works?

**Comment by bzuillsmith** [comment]
@paulcbetts I can only install the latest from npm's repo. No change. For some reason, installing straight from GitHub fails for me. I get ENOENT on ```lib/cli.js``` and it backs out. I'm not sure what would be dependent on that during install :/

**Comment by bzuillsmith** [comment]
@paulcbetts And I am proven wrong. A clone and ```npm install``` got the installNodeHeaders test to pass. I'll copy it over to my project and see if it works.

**Comment by bzuillsmith** [comment]
@paulcbetts Ok, I'm dumb. I was using this in a grunt task and I didn't set up ```this.async()``` correctly so it was exiting immediately after the first async call into the electron-rebuild api.

However, the tests don't all work and that was throwing me off too. Each time I ```npm test```, I have to first delete ```test-dist```. If I run a second time without cleaning, multiple tests fail including the ```installNodeHeader``` test.

**Comment by bzuillsmith** [comment]
@paulcbetts Oh and you'll have to publish the lastest. v0.2.3 still has some key missing fixes that I had to get from cloning the repo.

**Comment by paulcbetts** [comment]
@bzuillsmith Should be up to date now, try v0.2.3
